name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Package
        run: yarn package
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: xterm-player-pkg
          path: dist
